# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 54000  # 15 hrs
  - !type:DepartmentTimeRequirement
    department: Command
    time: 18000  # 5 hrs
  - !type:OverallPlaytimeRequirement
      time: 270000 # 75 hrs, borg already needs 60.
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-laws
  jobEntity: StationAiBrain
  applyTraits: false

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 216000 # 60 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-laws
  jobEntity: PlayerBorgGeneric
  applyTraits: false
