- type: entity
  id: CrateSecurityArmor
  parent: CrateSecgear
  name: Type I armor vest crate
  description: Contains three well-rounded Type I vests. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorBasic
        amount: 3

- type: entity
  id: CrateSecurityArmorBulletproof
  parent: CrateSecgear
  name: Type III armor vest crate
  description: Contains three bulletproof Type III vests. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorBulletproof
        amount: 3

- type: entity
  id: CrateSecurityHelmet
  parent: CrateSecgear
  name: helmet crate
  description: Contains three standard-issue brain buckets. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBasic
        amount: 3

- type: entity
  id: CrateSecurityNonlethal
  parent: CrateSecgear
  name: nonlethal stun crate
  description: Contains two disablers, stunbatons, flashes, and zipties. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: WeaponDisabler
        amount: 2
      - id: Stunbaton
        amount: 2
      - id: Flash
        amount: 2
      - id: Zipties # bare minimum, order actual restraints with your nonlethals
        amount: 2
#      - Pepperspray

- type: entity
  id: CrateSecurityRiot
  parent: CrateSecgear
  name: riot crate
  description: Contains two sets of riot armor, helmets, shields, protective masks, enforcers with beanbags shells, and beanbag shell boxes. Requires Armory access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorRiot
        amount: 2
      - id: ClothingHeadHelmetRiot
        amount: 2
      - id: WeaponShotgunEnforcerRubber
        amount: 2
      - id: BoxBeanbag
        amount: 2
      - id: RiotShield
        amount: 2
      - id: ClothingMaskGasSecurity
        amount: 2

- type: entity
  id: CrateSecuritySupplies
  parent: CrateSecgear
  name: officer gear crate
  description: Contains two SecGlasses, black gloves, jackboots, protective masks, and empty security belts. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingHandsGlovesColorBlack
        amount: 2
      - id: ClothingShoesBootsJackFilled
        amount: 2 # yes they get knives
      - id: ClothingMaskGasSecurity
        amount: 2
      - id: ClothingBeltSecurity
        amount: 2
      - id: BookSecurity
        amount: 2 # the law

- type: entity
  id: CrateRestraints
  parent: CrateSecgear
  name: restraints crate
  description: Contains a box of handcuffs and a box of zipties. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: BoxHandcuff
        amount: 1
      - id: BoxZiptie
        amount: 1

- type: entity
  id: CrateSecNonlethalThrowables
  parent: CrateSecgear
  name: nonlethal throwables crate
  description: Contains a box of flashbangs, box of stingers, box of tear gas, and four bolas. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: BoxFlashbang
        amount: 1
      - id: BoxStinger
        amount: 1
      - id: BoxTearGas
        amount: 1
      - id: Bola # replace with 4 e-bolas or e-bola box
        amount: 4

- type: entity
  id: CrateSecurityShield
  parent: CrateSecgear
  name: shield crate
  description: Contains two riot, bulletproof, and reflective shields. Requires Security access to open.
  components:
  - type: StorageFill
    contents:
      - id: RiotShield
        amount: 2
      - id: RiotBulletShield
        amount: 2
      - id: RiotLaserShield
        amount: 2

- type: entity
  id: CrateSecurityTrackingMindshieldImplants
  name: implanter crate
  description: Contains four mindshield implants, and four tracking implants. Requires Security access to open.
  parent: CrateSecgear
  components:
  - type: StorageFill
    contents:
      - id: MindShieldImplanter
        amount: 4
      - id: TrackingImplanter
        amount: 4

# Cosmetic Crates
